/**
 * Pure TypeScript Declarative Dynamic UI Renderer
 * 
 * Safely compiles JSON dynamic UI schemas generated by prompt-in-a-box agent loops
 * into visually stunning, interactive, responsive UI views.
 * Supports theme selection, component types, input form tracking, and execution routing.
 */

export interface UIComponent {
  type: 'header' | 'text' | 'button' | 'alert' | 'list' | 'input';
  id?: string;
  text?: string;
  intent?: 'info' | 'success' | 'warning' | 'danger';
  action?: 'trigger-run' | 'chrome-api' | 'none';
  apiMethod?: string;
  apiArgs?: any[];
  placeholder?: string;
  items?: string[];
  payload?: any;
}

export interface UISchema {
  title: string;
  theme?: 'default' | 'glassmorphic' | 'compact';
  components: UIComponent[];
}

const DYNAMIC_UI_KEY = '__pib_dynamic_ui';

export class UIRenderer {
  private container: HTMLElement;
  private formValues: Record<string, any> = {};
  private viewName: string;

  constructor(container: HTMLElement, viewName: string) {
    this.container = container;
    this.viewName = viewName;
  }

  /**
   * Loads the saved UI specification from chrome storage and renders it.
   */
  async loadAndRender(): Promise<void> {
    const data = await chrome.storage.local.get(DYNAMIC_UI_KEY);
    const spec = data[DYNAMIC_UI_KEY] as UISchema | undefined;

    if (!spec) {
      this.renderWelcomeState();
      return;
    }

    this.render(spec);
  }

  /**
   * Renders a fallback welcoming view if no dynamic UI has been posted yet.
   */
  private renderWelcomeState(): void {
    this.container.innerHTML = `
      <div class="welcome-container">
        <div class="welcome-logo">🤖</div>
        <h3>Agent Dynamic View</h3>
        <p>No active runtime interface has been posted by the agent yet.</p>
        <button id="triggerWelcomeRun" class="primary-btn">Initialize Agent</button>
      </div>
    `;
    
    const btn = this.container.querySelector('#triggerWelcomeRun');
    if (btn) {
      btn.addEventListener('click', async () => {
        const text = btn.textContent;
        btn.textContent = 'Initializing...';
        (btn as HTMLButtonElement).disabled = true;
        try {
          await chrome.runtime.sendMessage({
            type: 'ui-opened',
            view: this.viewName
          });
        } finally {
          btn.textContent = text;
          (btn as HTMLButtonElement).disabled = false;
        }
      });
    }
  }

  /**
   * Main render entry point. Builds DOM nodes safely to prevent XSS.
   */
  render(spec: UISchema): void {
    this.container.innerHTML = '';
    this.formValues = {};

    // Apply overall theme classes to container
    this.container.className = `ui-container theme-${spec.theme || 'default'}`;

    // 1. Render View Title
    const titleEl = document.createElement('h1');
    titleEl.className = 'ui-title';
    titleEl.textContent = spec.title;
    this.container.appendChild(titleEl);

    // 2. Render all components
    const componentWrapper = document.createElement('div');
    componentWrapper.className = 'ui-components';

    for (const comp of spec.components) {
      const el = this.createComponent(comp);
      if (el) {
        componentWrapper.appendChild(el);
      }
    }

    this.container.appendChild(componentWrapper);
  }

  /**
   * Factory function that creates individual component nodes.
   */
  private createComponent(comp: UIComponent): HTMLElement | null {
    switch (comp.type) {
      case 'header': {
        const el = document.createElement('h2');
        el.className = 'ui-header-element';
        el.textContent = comp.text || '';
        return el;
      }

      case 'text': {
        const el = document.createElement('p');
        el.className = 'ui-text-element';
        el.textContent = comp.text || '';
        return el;
      }

      case 'alert': {
        const el = document.createElement('div');
        el.className = `ui-alert intent-${comp.intent || 'info'}`;
        
        // Add indicator icon
        const iconEl = document.createElement('span');
        iconEl.className = 'alert-icon';
        iconEl.innerHTML = this.getAlertIcon(comp.intent || 'info');
        el.appendChild(iconEl);

        const textEl = document.createElement('span');
        textEl.className = 'alert-text';
        textEl.textContent = comp.text || '';
        el.appendChild(textEl);

        return el;
      }

      case 'list': {
        if (!comp.items || comp.items.length === 0) return null;
        const el = document.createElement('ul');
        el.className = 'ui-list';
        for (const item of comp.items) {
          const li = document.createElement('li');
          li.textContent = item;
          el.appendChild(li);
        }
        return el;
      }

      case 'input': {
        if (!comp.id) return null;
        const wrapper = document.createElement('div');
        wrapper.className = 'ui-input-wrapper';

        const label = document.createElement('label');
        label.setAttribute('for', comp.id);
        label.textContent = comp.text || '';
        wrapper.appendChild(label);

        const input = document.createElement('input');
        input.type = 'text';
        input.id = comp.id;
        input.placeholder = comp.placeholder || '';
        input.className = 'ui-input-field';

        // Track state changes dynamically
        input.addEventListener('input', () => {
          this.formValues[comp.id!] = input.value;
        });

        wrapper.appendChild(input);
        return wrapper;
      }

      case 'button': {
        const el = document.createElement('button');
        el.className = `ui-btn btn-intent-${comp.intent || 'info'}`;
        el.textContent = comp.text || 'Button';

        if (comp.id) {
          el.setAttribute('id', comp.id);
        }

        // Click interaction logic
        el.addEventListener('click', async () => {
          el.classList.add('btn-loading');
          const originalText = el.textContent;
          el.textContent = 'Processing...';
          el.disabled = true;

          try {
            if (comp.action === 'chrome-api' && comp.apiMethod) {
              await this.executeChromeAPI(comp.apiMethod, comp.apiArgs || []);
            } else if (comp.action === 'trigger-run') {
              // Combine default payload with dynamic inputs
              const payload = {
                ...comp.payload,
                formValues: this.formValues
              };
              await chrome.runtime.sendMessage({
                type: 'ui-interaction',
                componentId: comp.id || 'unnamed',
                action: comp.action,
                payload
              });
            }
          } catch (err) {
            console.error('Interaction execution error:', err);
          } finally {
            el.classList.remove('btn-loading');
            el.textContent = originalText;
            el.disabled = false;
          }
        });

        return el;
      }

      default:
        return null;
    }
  }

  /**
   * Runs direct Chrome API calls safely.
   */
  private async executeChromeAPI(methodName: string, args: any[]): Promise<void> {
    const parts = methodName.split('.');
    let api: any = chrome;
    
    for (const part of parts) {
      if (!api[part]) {
        throw new Error(`Chrome API chrome.${methodName} not found.`);
      }
      api = api[part];
    }
    
    if (typeof api !== 'function') {
      throw new Error(`chrome.${methodName} is not a function.`);
    }

    return new Promise((resolve, reject) => {
      try {
        api(...args, (result: any) => {
          if (chrome.runtime.lastError) {
            reject(new Error(chrome.runtime.lastError.message));
          } else {
            resolve(result);
          }
        });
      } catch (err) {
        reject(err);
      }
    });
  }

  /**
   * Dynamic SVG icon builder depending on warning/success intent.
   */
  private getAlertIcon(intent: string): string {
    switch (intent) {
      case 'success':
        return '<svg viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" /></svg>';
      case 'warning':
        return '<svg viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" /></svg>';
      case 'danger':
        return '<svg viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" /></svg>';
      default:
        return '<svg viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" /></svg>';
    }
  }
}
